-- Ràng buộc khóa ngoại (Foreign Key)
ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_CATEGORIES 
FOREIGN KEY (CategoryId) 
REFERENCES CATEGORIES(CategoryId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng CATEGORIES

ALTER TABLE CUSTOMER_PAYMENT
ADD CONSTRAINT FK_CUSTOMER_PAYMENT 
FOREIGN KEY (PaymentId) 
REFERENCES PAYMENT(PaymentId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng PAYMENT

ALTER TABLE CARTS
ADD CONSTRAINT FK_CARTS_PRODUCTS 
FOREIGN KEY (ProductId) 
REFERENCES PRODUCTS(ProductId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng PRODUCTS

ALTER TABLE CARTS
ADD CONSTRAINT FK_CARTS_USERS 
FOREIGN KEY (UserId) 
REFERENCES USERS(UserId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng USERS

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_USERS 
FOREIGN KEY (UserId) 
REFERENCES USERS(UserId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng USERS

ALTER TABLE ORDER_PRODUCTS
ADD CONSTRAINT FK_ORDER_PRODUCTS_ORDER 
FOREIGN KEY (OrderDetailsId) 
REFERENCES ORDERS(OrderDetailsId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng ORDERS

ALTER TABLE ORDER_PRODUCTS
ADD CONSTRAINT FK_ORDER_PRODUCTS_PRODUCTS 
FOREIGN KEY (ProductId) 
REFERENCES PRODUCTS(ProductId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng PRODUCTS

ALTER TABLE ORDER_PAYMENT
ADD CONSTRAINT FK_ORDER_PAYMENT_ORDER 
FOREIGN KEY (OrderDetailsId) 
REFERENCES ORDERS(OrderDetailsId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng ORDERS

ALTER TABLE ORDER_PAYMENT
ADD CONSTRAINT FK_ORDER_PAYMENT_PAYMENT 
FOREIGN KEY (PaymentId) 
REFERENCES PAYMENT(PaymentId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng PAYMENT

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_USERS 
FOREIGN KEY (UserId) 
REFERENCES USERS(UserId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng USERS

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_PRODUCTS 
FOREIGN KEY (ProductId) 
REFERENCES PRODUCTS(ProductId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng PRODUCTS

ALTER TABLE DELIVERY
ADD CONSTRAINT FK_DELIVERY_ORDERS 
FOREIGN KEY (OrderDetailsId) 
REFERENCES ORDERS(OrderDetailsId) 
ON DELETE CASCADE; -- Ràng buộc khóa ngoại đến bảng ORDERS

-- Ràng buộc kiểm tra dữ liệu (CHECK)
ALTER TABLE PRODUCTS
ADD CONSTRAINT CK_PRODUCTS_QUANTITY 
CHECK (Quantity > 0); -- Ràng buộc kiểm tra số lượng sản phẩm phải lớn hơn 0

ALTER TABLE ORDER_PRODUCTS
ADD CONSTRAINT CK_ORDER_PRODUCTS_QUANTITY 
CHECK (Quantity > 0); -- Ràng buộc kiểm tra số lượng sản phẩm trong đơn hàng phải lớn hơn 0

ALTER TABLE REVIEWS
ADD CONSTRAINT CK_REVIEWS_RATING 
CHECK (Rating BETWEEN 1 AND 5); -- Ràng buộc kiểm tra đánh giá phải trong khoảng từ 1 đến 5

ALTER TABLE COUPONS
ADD CONSTRAINT CK_COUPONS_DISCOUNT 
CHECK (DiscountPercentage BETWEEN 0 AND 100); -- Ràng buộc kiểm tra tỷ lệ giảm giá phải trong khoảng từ 0 đến 100

